'use client'

import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import 'react-loading-skeleton/dist/skeleton.css'

import type { Metadata } from 'next'
//redux
import {Providers} from "@/utils/redux/provider";
export const metadata: Metadata = {
  title: 'Reddit clone',
  description: 'Generated by create next app',
}

import { Helmet, HelmetProvider } from 'react-helmet-async';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <body>
        <HelmetProvider>
            <Helmet>
                <link rel="icon" type="image/png" href='/images/favicon.ico' sizes="16x16" />
            </Helmet>
          <Providers>
            {children}
          </Providers> 
        </HelmetProvider>
      </body>
    </html>
  )
}
