'use client'


import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import 'react-loading-skeleton/dist/skeleton.css'

//redux
import {Providers} from "@/utils/redux/provider";


import { Helmet, HelmetProvider } from 'react-helmet-async';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


  return (
    <html lang="en">
      <title>Reddit clone</title>
        <meta name='description' content='Generated by create next app' />
        <link rel="icon" type="image/png" href='/images/favicon.ico' sizes="16x16" />
      <body>
        <HelmetProvider>
          <Providers>
            {children}
          </Providers> 
        </HelmetProvider>
      </body>
    </html>
  )
}
